# Generated by Django 3.1.7 on 2021-02-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motorista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='passageiro',
            field=models.BooleanField(default=False),
        ),
    ]
